before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64


archives:
  - format_overrides:
      - goos: windows
        format: zip

checksum:
  disable: true

changelog:
  skip: true